### ISSUE TITLE
Include sbcs.full.js in Node Package

### ISSUE THREAD

**Issue by stephenegriffin** [SheetJS/js-codepage#14]
I've found I can get by with sbcs.full.js and not need to load the 2mb cptable.js. However sbcs.full.js isn't available via npm (that I can find). Can we get it added to the package?

**Comment by stephenegriffin** [comment]
Confirmed: codepage@1.3.1 has this file under dist. c5339be089338130529c2167587986af315219f9 slimmed up the package with the side effect of removing this file. Per documentation on https://www.npmjs.com/package/codepage I believe this was unintended.

Recommended fix: Add sbcs.full.js (and maybe sbcs.js) directly to package.json

**Comment by SheetJSDev** [comment]
@stephenegriffin we just pushed 1.11.1 that added sbcs.full.js to the node module.  [UNPKG has the file now!](https://unpkg.com/codepage@1.11.1/dist/sbcs.full.js)  Since the code wasn't modified, we didn't rebuild the scripts with the new version number, but 1.12.0 will show the correct version number in the scripts.

**Comment by stephenegriffin** [comment]
Awesome - thanks for the unpkg tip too. Totally using that.
